name: Java CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run tests
        run: ./gradlew test
      - name: Generate code coverage report
        run: ./gradlew jacocoTestReport
      - name: Check code coverage
        run: ./gradlew jacocoTestCoverageVerification
  check-failing-tests:
    needs: build
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check failing tests
        run: exit 1
  check-code-coverage:
    needs: build
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check code coverage threshold
        run: exit 2
